### ISSUE TITLE
HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by harrykipper** [tomslee/airbnbny#2]
./airbnb.py -ac "Florence"
Failure retrieving https://www.airbnb.com/s/Florence
Traceback (most recent call last):
  File "./airbnb.py", line 345, in get_search_page
    response = urllib.request.urlopen(url, timeout=URL_TIMEOUT)
  File "/usr/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 471, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 509, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 589, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by tomslee** [comment]
I took the Airbnb code off GitHub because Airbnb is making it more difficult to scrape their web site - hence errors like this from their site. Sorry I can't help fix this one. Do email me if you want to pursue conversation (tom at tomslee dot net)
